services:
  postgres:
    image: postgres:15
    container_name: icpc_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: icpc
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # frontend:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: icpc_frontend
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - DATABASE_URL=postgresql://postgres:password@postgres:5432/icpc?schema=public
  #   depends_on:
  #     - postgres

volumes:
  pgdata: