name: Docker Image CI

on:
  push:
    tags:
      - 'latest'
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout code
        uses: actions/checkout@v3

      -
          name: Debug runner
          run: ls -la && ls -la icpc_front
      -
          name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ vars.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ${{ github.workspace }}/icpc_front
          file: ${{ github.workspace }}/icpc_front/Dockerfile
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/icpc_web:latest
